import type { NextPage } from 'next'
import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { data: session } = useSession()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      {session && (
        <div>
          <ul>
            <li>
              <Link href="/me ">
                <div>Me</div>
              </Link>
            </li>
            <li>
              <Link href="/protected">
                <div>Protected</div>
              </Link>
            </li>
            <li>
              <Link href="/admin">
                <div>Admin</div>
              </Link>
            </li>
          </ul>
          Signed in as {session.user.email} <br />
          <button onClick={() => signOut()}>Sign out</button>
        </div>
      )}
      {!session && (
        <div>
          Not signed in <br />
          <button onClick={() => signIn()}>Sign in</button>
        </div>
      )}
      </main>
    </div>
  )
}

export default Home
